let currentQuestions = [];

function getRandomNumber(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRange(difficulty) {
  if (difficulty === "easy") return { min: 1, max: 20 };
  if (difficulty === "medium") return { min: 10, max: 100 };
  return { min: 50, max: 999 };
}

function createQuestion(operation, difficulty) {
  const range = getRange(difficulty);
  let a = getRandomNumber(range.min, range.max);
  let b = getRandomNumber(range.min, range.max);

  if (operation === "mixed") {
    const ops = ["addition", "subtraction", "multiplication", "division"];
    operation = ops[getRandomNumber(0, ops.length - 1)];
  }

  if (operation === "addition") {
    return { text: `${a} + ${b} =`, answer: a + b };
  }

  if (operation === "subtraction") {
    if (b > a) [a, b] = [b, a];
    return { text: `${a} - ${b} =`, answer: a - b };
  }

  if (operation === "multiplication") {
    if (difficulty === "easy") {
      a = getRandomNumber(1, 10);
      b = getRandomNumber(1, 10);
    } else if (difficulty === "medium") {
      a = getRandomNumber(2, 12);
      b = getRandomNumber(2, 12);
    } else {
      a = getRandomNumber(10, 99);
      b = getRandomNumber(2, 12);
    }
    return { text: `${a} × ${b} =`, answer: a * b };
  }

  if (operation === "division") {
    b = getRandomNumber(2, 12);
    const result = getRandomNumber(2, 12);
    a = b * result;
    return { text: `${a} ÷ ${b} =`, answer: result };
  }

  return { text: `${a} + ${b} =`, answer: a + b };
}

function generateWorksheet() {
  const grade = document.getElementById("grade").value;
  const operation = document.getElementById("operation").value;
  const difficulty = document.getElementById("difficulty").value;
  const questionCount = parseInt(document.getElementById("questionCount").value);
  const studentName = document.getElementById("studentName").value.trim();

  currentQuestions = [];

  for (let i = 0; i < questionCount; i++) {
    currentQuestions.push(createQuestion(operation, difficulty));
  }

  const worksheet = document.getElementById("worksheet");
  const questionsContainer = document.getElementById("questions");

  worksheet.querySelector(".worksheet-header").innerHTML = `
    <h2>Math Worksheet</h2>
    <p>Generated by TeachSheet AI</p>
    <div class="meta">
      <div><strong>Name:</strong> ${studentName || "________________"}</div>
      <div><strong>Grade:</strong> ${grade}</div>
      <div><strong>Operation:</strong> ${formatOperation(operation)}</div>
      <div><strong>Difficulty:</strong> ${capitalize(difficulty)}</div>
    </div>
  `;

  questionsContainer.className = "questions";
  questionsContainer.innerHTML = "";

  currentQuestions.forEach((q, index) => {
    const div = document.createElement("div");
    div.className = "question";
    div.innerHTML = `<strong>${index + 1}.</strong> ${q.text} <span class="answer-line"></span>`;
    questionsContainer.appendChild(div);
  });

  const oldAnswerKey = document.querySelector(".answer-key");
  if (oldAnswerKey) oldAnswerKey.remove();

  const answerKey = document.createElement("div");
  answerKey.className = "answer-key";
  answerKey.innerHTML = `
    <h3>Answer Key</h3>
    <div class="answer-grid">
      ${currentQuestions.map((q, i) => `<div>${i + 1}) ${q.answer}</div>`).join("")}
    </div>
  `;
  worksheet.appendChild(answerKey);
}

function formatOperation(operation) {
  const names = {
    addition: "Addition",
    subtraction: "Subtraction",
    multiplication: "Multiplication",
    division: "Division",
    mixed: "Mixed Operations"
  };
  return names[operation] || operation;
}

function capitalize(text) {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function clearWorksheet() {
  currentQuestions = [];
  document.getElementById("worksheet").innerHTML = `
    <div class="worksheet-header">
      <h2>Math Worksheet</h2>
      <p>Choose settings and click Generate Worksheet.</p>
    </div>
    <div id="questions" class="questions empty">No worksheet generated yet.</div>
  `;
}

function downloadPDF() {
  if (currentQuestions.length === 0) {
    alert("Please generate a worksheet first.");
    return;
  }

  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF("p", "mm", "a4");

  const grade = document.getElementById("grade").value;
  const operation = document.getElementById("operation").value;
  const difficulty = document.getElementById("difficulty").value;
  const studentName = document.getElementById("studentName").value.trim();

  let y = 20;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("TeachSheet AI", 105, y, { align: "center" });

  y += 10;
  pdf.setFontSize(16);
  pdf.text("Math Worksheet", 105, y, { align: "center" });

  y += 14;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);

  pdf.text(`Name: ${studentName || "________________________"}`, 20, y);
  pdf.text(`Grade: ${grade}`, 130, y);

  y += 8;
  pdf.text(`Operation: ${formatOperation(operation)}`, 20, y);
  pdf.text(`Difficulty: ${capitalize(difficulty)}`, 130, y);

  y += 12;
  pdf.line(20, y, 190, y);
  y += 12;

  pdf.setFontSize(14);

  currentQuestions.forEach((q, index) => {
    if (y > 260) {
      pdf.addPage();
      y = 20;
    }

    const questionText = `${index + 1}. ${q.text} __________________`;

    if (index % 2 === 0) {
      pdf.text(questionText, 20, y);
    } else {
      pdf.text(questionText, 110, y);
      y += 14;
    }
  });

  pdf.addPage();
  y = 20;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("Answer Key", 105, y, { align: "center" });

  y += 15;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(12);

  currentQuestions.forEach((q, index) => {
    if (y > 270) {
      pdf.addPage();
      y = 20;
    }

    pdf.text(`${index + 1}) ${q.answer}`, 25 + ((index % 4) * 45), y);

    if (index % 4 === 3) y += 10;
  });

  pdf.save("teachsheet-ai-worksheet.pdf");
}
