let questions = [];
let answers = [];
let currentPage = 0;
let currentTheme = "blue";
let zoomLevel = 1;
let previewPages = [];

const QUESTIONS_PER_PAGE = 10;

document.addEventListener("DOMContentLoaded", () => {
  renderInitialPreview();
});

function generateWorksheet() {
  const teacherName = getValue("teacherName", "—");
  const schoolName = getValue("schoolName", "—");
  const subjectName = getValue("subjectName", "Mathematics");
  const className = getValue("className", "—");
  const studentName = getValue("studentName", "—");
  const grade = getValue("grade", "Grade 2");
  const operation = getValue("operation", "addition");
  const difficulty = getValue("difficulty", "medium");
  const questionCount = Number(getValue("questionCount", 15));

  questions = [];
  answers = [];
  currentPage = 0;

  for (let i = 1; i <= questionCount; i++) {
    const item = createQuestion(i, operation, difficulty);
    questions.push(item);
    answers.push(item);
  }

  previewPages = paginate(questions, QUESTIONS_PER_PAGE);

  renderWorksheetPage({
    teacherName,
    schoolName,
    subjectName,
    className,
    studentName,
    grade,
    pageIndex: currentPage
  });

  renderThumbnails();
}

function renderWorksheetPage(data) {
  const worksheet = document.getElementById("worksheet");
  const pageData = previewPages[data.pageIndex] || [];

  worksheet.className = `a4-page theme-${currentTheme}`;
  worksheet.style.transform = `scale(${zoomLevel})`;
  worksheet.style.transformOrigin = "top center";

  worksheet.innerHTML = `
    <div class="a4-header">
      <div class="logo-mark">TS</div>

      <div class="a4-title-block">
        <h2>${escapeHtml(data.subjectName)} Worksheet</h2>
        <p>${escapeHtml(data.grade)} · Generated worksheet</p>
      </div>

      <div class="a4-brand">
        TeachSheet AI
      </div>
    </div>

    <div class="a4-info-grid">
      <div><strong>Teacher:</strong> ${escapeHtml(data.teacherName)}</div>
      <div><strong>School:</strong> ${escapeHtml(data.schoolName)}</div>
      <div><strong>Class:</strong> ${escapeHtml(data.className)}</div>
      <div><strong>Student:</strong> ${escapeHtml(data.studentName)}</div>
      <div><strong>Date:</strong> ${new Date().toLocaleDateString()}</div>
      <div><strong>Grade:</strong> ${escapeHtml(data.grade)}</div>
    </div>

    <div class="a4-divider"></div>

    <div id="questions" class="questions">
      ${pageData.map(q => `
        <div class="question">
          ${q.number}. ${q.text}
          <span class="answer-line"></span>
        </div>
      `).join("")}
    </div>

    <div class="a4-footer">
      Generated by TeachSheet AI · Page ${data.pageIndex + 1}
    </div>
  `;

  updatePageInfo();
}

function createQuestion(number, operation, difficulty) {
  const range = getRange(difficulty);
  let a = random(range.min, range.max);
  let b = random(range.min, range.max);

  if (operation === "mixed") {
    const ops = ["addition", "subtraction", "multiplication", "division"];
    operation = ops[random(0, ops.length - 1)];
  }

  if (operation === "addition") {
    return {
      number,
      text: `${a} + ${b} =`,
      answer: a + b
    };
  }

  if (operation === "subtraction") {
    if (b > a) [a, b] = [b, a];
    return {
      number,
      text: `${a} - ${b} =`,
      answer: a - b
    };
  }

  if (operation === "multiplication") {
    a = random(2, difficulty === "hard" ? 12 : 10);
    b = random(2, difficulty === "hard" ? 12 : 10);

    return {
      number,
      text: `${a} × ${b} =`,
      answer: a * b
    };
  }

  if (operation === "division") {
    b = random(2, 10);
    const result = random(2, 12);
    a = b * result;

    return {
      number,
      text: `${a} ÷ ${b} =`,
      answer: result
    };
  }

  return {
    number,
    text: `${a} + ${b} =`,
    answer: a + b
  };
}

function getRange(difficulty) {
  if (difficulty === "easy") return { min: 1, max: 20 };
  if (difficulty === "hard") return { min: 50, max: 999 };
  return { min: 10, max: 100 };
}

function previousPreviewPage() {
  if (currentPage > 0) {
    currentPage--;
    refreshCurrentPage();
  }
}

function nextPreviewPage() {
  if (currentPage < previewPages.length) {
    currentPage++;
    if (currentPage === previewPages.length) {
      renderAnswerSheet();
    } else {
      refreshCurrentPage();
    }
  }
}

function refreshCurrentPage() {
  renderWorksheetPage({
    teacherName: getValue("teacherName", "—"),
    schoolName: getValue("schoolName", "—"),
    subjectName: getValue("subjectName", "Mathematics"),
    className: getValue("className", "—"),
    studentName: getValue("studentName", "—"),
    grade: getValue("grade", "Grade 2"),
    pageIndex: currentPage
  });

  renderThumbnails();
}

function renderAnswerSheet() {
  const worksheet = document.getElementById("worksheet");

  worksheet.className = `a4-page theme-${currentTheme}`;
  worksheet.style.transform = `scale(${zoomLevel})`;
  worksheet.style.transformOrigin = "top center";

  worksheet.innerHTML = `
    <div class="a4-header">
      <div class="logo-mark">TS</div>

      <div class="a4-title-block">
        <h2>Answer Sheet</h2>
        <p>Correction key for the generated worksheet</p>
      </div>

      <div class="a4-brand">TeachSheet AI</div>
    </div>

    <div class="a4-divider"></div>

    <div class="answer-key">
      <h3>Answers</h3>

      <div class="answer-grid">
        ${answers.map(a => `
          <div>${a.number}. ${a.answer}</div>
        `).join("")}
      </div>
    </div>

    <div class="a4-footer">
      Generated by TeachSheet AI · Answer Sheet
    </div>
  `;

  updatePageInfo();
  renderThumbnails();
}

function renderThumbnails() {
  const box = document.getElementById("pageThumbnails");
  if (!box) return;

  box.innerHTML = "";

  previewPages.forEach((_, index) => {
    const div = document.createElement("div");
    div.className = `page-thumb ${index === currentPage ? "active-thumb" : ""}`;
    div.innerHTML = `<span>${index + 1}</span><strong>Worksheet</strong>`;
    div.onclick = () => {
      currentPage = index;
      refreshCurrentPage();
    };
    box.appendChild(div);
  });

  const answerDiv = document.createElement("div");
  answerDiv.className = `page-thumb ${currentPage === previewPages.length ? "active-thumb" : ""}`;
  answerDiv.innerHTML = `<span>${previewPages.length + 1}</span><strong>Answers</strong>`;
  answerDiv.onclick = () => {
    currentPage = previewPages.length;
    renderAnswerSheet();
  };
  box.appendChild(answerDiv);
}

function updateZoom(value) {
  let zoom = Number(value) / 100;

  if (!zoom || zoom < 0.3) {
    zoom = 1;
  }

  zoomLevel = zoom;

  const worksheet = document.getElementById("worksheet");
  const zoomValue = document.getElementById("zoomValue");

  if (worksheet) {
    worksheet.style.transform = `scale(${zoomLevel})`;
    worksheet.style.transformOrigin = "top center";
  }

  if (zoomValue) {
    zoomValue.textContent = `${Math.round(zoomLevel * 100)}%`;
  }
}

function setTheme(theme) {
  currentTheme = theme;
  const worksheet = document.getElementById("worksheet");

  if (worksheet) {
    worksheet.classList.remove("theme-blue", "theme-green", "theme-dark");
    worksheet.classList.add(`theme-${theme}`);
  }
}

function downloadPDF() {
  const element = document.getElementById("worksheet");

  if (!element) return;

  const options = {
    margin: 0,
    filename: "TeachSheet-AI-Worksheet.pdf",
    image: {
      type: "jpeg",
      quality: 1
    },
    html2canvas: {
      scale: 2,
      useCORS: true
    },
    jsPDF: {
      unit: "mm",
      format: "a4",
      orientation: "portrait"
    }
  };

  html2pdf().set(options).from(element).save();
}

function clearWorksheet() {
  questions = [];
  answers = [];
  previewPages = [];
  currentPage = 0;
  renderInitialPreview();
}

function renderInitialPreview() {
  const worksheet = document.getElementById("worksheet");
  if (!worksheet) return;

  worksheet.className = `a4-page theme-${currentTheme}`;

  worksheet.innerHTML = `
    <div class="a4-header">
      <div class="logo-mark">TS</div>

      <div class="a4-title-block">
        <h2>Math Worksheet</h2>
        <p>Choose settings and generate your worksheet.</p>
      </div>

      <div class="a4-brand">
        TeachSheet AI
      </div>
    </div>

    <div class="a4-info-grid">
      <div><strong>Teacher:</strong> —</div>
      <div><strong>School:</strong> —</div>
      <div><strong>Class:</strong> —</div>
      <div><strong>Student:</strong> —</div>
      <div><strong>Date:</strong> —</div>
      <div><strong>Grade:</strong> —</div>
    </div>

    <div class="a4-divider"></div>

    <div id="questions" class="questions empty a4-empty">
      No worksheet generated yet.
    </div>

    <div class="a4-footer">
      Generated by TeachSheet AI · Page 1
    </div>
  `;

  updatePageInfo();
}

function updatePageInfo() {
  const pageInfo = document.getElementById("pageInfo");
  if (!pageInfo) return;

  const total = previewPages.length > 0 ? previewPages.length + 1 : 1;
  const current = previewPages.length > 0 ? currentPage + 1 : 1;

  pageInfo.textContent = `Page ${current} of ${total}`;
}

function paginate(items, perPage) {
  const pages = [];

  for (let i = 0; i < items.length; i += perPage) {
    pages.push(items.slice(i, i + perPage));
  }

  return pages;
}

function getValue(id, fallback) {
  const el = document.getElementById(id);
  return el && el.value ? el.value.trim() : fallback;
}

function random(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function escapeHtml(text) {
  return String(text)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
