let currentQuestions = [];

function getRandomNumber(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function normalizeText(text) {
  return String(text || "").trim();
}

function getRangeByGradeAndDifficulty(grade, difficulty) {
  const gradeNumber = parseInt(String(grade).replace(/\D/g, ""), 10) || 2;
  const level = String(difficulty).toLowerCase();

  if (gradeNumber <= 1) {
    if (level === "easy") return { min: 1, max: 10 };
    if (level === "medium") return { min: 1, max: 20 };
    return { min: 1, max: 50 };
  }

  if (gradeNumber === 2) {
    if (level === "easy") return { min: 1, max: 20 };
    if (level === "medium") return { min: 10, max: 100 };
    return { min: 50, max: 200 };
  }

  if (gradeNumber === 3) {
    if (level === "easy") return { min: 10, max: 100 };
    if (level === "medium") return { min: 50, max: 500 };
    return { min: 100, max: 999 };
  }

  if (gradeNumber === 4) {
    if (level === "easy") return { min: 50, max: 500 };
    if (level === "medium") return { min: 100, max: 999 };
    return { min: 500, max: 5000 };
  }

  if (level === "easy") return { min: 100, max: 999 };
  if (level === "medium") return { min: 500, max: 5000 };
  return { min: 1000, max: 9999 };
}

function createQuestion(operation, grade, difficulty) {
  let selectedOperation = operation;

  if (selectedOperation === "mixed") {
    const operations = ["addition", "subtraction", "multiplication", "division"];
    selectedOperation = operations[getRandomNumber(0, operations.length - 1)];
  }

  const range = getRangeByGradeAndDifficulty(grade, difficulty);
  let a = getRandomNumber(range.min, range.max);
  let b = getRandomNumber(range.min, range.max);

  if (selectedOperation === "addition") {
    return {
      operation: "Addition",
      text: `${a} + ${b} =`,
      answer: a + b
    };
  }

  if (selectedOperation === "subtraction") {
    if (b > a) {
      const temp = a;
      a = b;
      b = temp;
    }

    return {
      operation: "Subtraction",
      text: `${a} - ${b} =`,
      answer: a - b
    };
  }

  if (selectedOperation === "multiplication") {
    const gradeNumber = parseInt(String(grade).replace(/\D/g, ""), 10) || 2;
    const level = String(difficulty).toLowerCase();

    if (gradeNumber <= 2 || level === "easy") {
      a = getRandomNumber(1, 10);
      b = getRandomNumber(1, 10);
    } else if (gradeNumber <= 4 || level === "medium") {
      a = getRandomNumber(2, 12);
      b = getRandomNumber(2, 12);
    } else {
      a = getRandomNumber(10, 99);
      b = getRandomNumber(2, 12);
    }

    return {
      operation: "Multiplication",
      text: `${a} × ${b} =`,
      answer: a * b
    };
  }

  if (selectedOperation === "division") {
    const divisor = getRandomNumber(2, 12);
    const quotient = getRandomNumber(2, 12);
    const dividend = divisor * quotient;

    return {
      operation: "Division",
      text: `${dividend} ÷ ${divisor} =`,
      answer: quotient
    };
  }

  return {
    operation: "Addition",
    text: `${a} + ${b} =`,
    answer: a + b
  };
}

function formatOperation(operation) {
  const names = {
    addition: "Addition",
    subtraction: "Subtraction",
    multiplication: "Multiplication",
    division: "Division",
    mixed: "Mixed Operations"
  };

  return names[operation] || operation;
}

function getWorksheetData() {
  return {
    grade: document.getElementById("grade").value,
    operation: document.getElementById("operation").value,
    difficulty: document.getElementById("difficulty").value,
    questionCount: parseInt(document.getElementById("questionCount").value, 10),
    studentName: normalizeText(document.getElementById("studentName").value)
  };
}

function generateWorksheet() {
  const data = getWorksheetData();

  currentQuestions = [];

  for (let i = 0; i < data.questionCount; i++) {
    currentQuestions.push(
      createQuestion(data.operation, data.grade, data.difficulty)
    );
  }

  renderWorksheet(data);
}

function renderWorksheet(data) {
  const worksheet = document.getElementById("worksheet");
  const questionsContainer = document.getElementById("questions");

  worksheet.querySelector(".worksheet-header").innerHTML = `
    <h2>Math Worksheet</h2>
    <p>Generated by TeachSheet AI</p>

    <div class="meta">
      <div><strong>Name:</strong> ${data.studentName || "________________"}</div>
      <div><strong>Grade:</strong> ${data.grade}</div>
      <div><strong>Operation:</strong> ${formatOperation(data.operation)}</div>
      <div><strong>Difficulty:</strong> ${data.difficulty}</div>
    </div>
  `;

  questionsContainer.className = "questions";
  questionsContainer.innerHTML = "";

  currentQuestions.forEach((question, index) => {
    const questionElement = document.createElement("div");
    questionElement.className = "question";
    questionElement.innerHTML = `
      <strong>${index + 1}.</strong>
      ${question.text}
      <span class="answer-line"></span>
    `;
    questionsContainer.appendChild(questionElement);
  });

  const oldAnswerKey = worksheet.querySelector(".answer-key");
  if (oldAnswerKey) {
    oldAnswerKey.remove();
  }

  const answerKey = document.createElement("div");
  answerKey.className = "answer-key";
  answerKey.innerHTML = `
    <h3>Answer Key</h3>
    <div class="answer-grid">
      ${currentQuestions
        .map((question, index) => `<div>${index + 1}) ${question.answer}</div>`)
        .join("")}
    </div>
  `;

  worksheet.appendChild(answerKey);
}

function clearWorksheet() {
  currentQuestions = [];

  const worksheet = document.getElementById("worksheet");

  worksheet.innerHTML = `
    <div class="worksheet-header">
      <h2>Math Worksheet</h2>
      <p>Choose settings and generate your worksheet.</p>
    </div>

    <div id="questions" class="questions empty">
      No worksheet generated yet.
    </div>
  `;
}

function downloadPDF() {
  if (!currentQuestions.length) {
    alert("Please generate a worksheet first.");
    return;
  }

  if (!window.jspdf || !window.jspdf.jsPDF) {
    alert("PDF library is not loaded. Please check your internet connection.");
    return;
  }

  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF("p", "mm", "a4");

  const data = getWorksheetData();
  const today = new Date().toLocaleDateString();

  let y = 18;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("TeachSheet AI", 105, y, { align: "center" });

  y += 9;

  pdf.setFontSize(15);
  pdf.text("Math Worksheet", 105, y, { align: "center" });

  y += 12;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);

  pdf.text(`Name: ${data.studentName || "________________________"}`, 18, y);
  pdf.text(`Date: ${today}`, 145, y);

  y += 7;

  pdf.text(`Grade: ${data.grade}`, 18, y);
  pdf.text(`Operation: ${formatOperation(data.operation)}`, 75, y);
  pdf.text(`Difficulty: ${data.difficulty}`, 145, y);

  y += 8;

  pdf.setLineWidth(0.4);
  pdf.line(18, y, 192, y);

  y += 12;

  pdf.setFontSize(13);

  currentQuestions.forEach((question, index) => {
    if (y > 265) {
      addFooter(pdf);
      pdf.addPage();
      y = 18;
    }

    const leftColumn = index % 2 === 0;
    const x = leftColumn ? 20 : 110;

    pdf.text(`${index + 1}. ${question.text}`, x, y);
    pdf.line(x + 37, y + 1, x + 75, y + 1);

    if (!leftColumn) {
      y += 14;
    }
  });

  addFooter(pdf);

  pdf.addPage();

  y = 20;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("Answer Key", 105, y, { align: "center" });

  y += 14;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(12);

  currentQuestions.forEach((question, index) => {
    if (y > 270) {
      addFooter(pdf);
      pdf.addPage();
      y = 20;
    }

    const column = index % 4;
    const x = 22 + column * 45;

    pdf.text(`${index + 1}) ${question.answer}`, x, y);

    if (column === 3) {
      y += 10;
    }
  });

  addFooter(pdf);

  pdf.save("teachsheet-ai-worksheet.pdf");
}

function addFooter(pdf) {
  const pageHeight = pdf.internal.pageSize.height;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text(
    "Generated by TeachSheet AI",
    105,
    pageHeight - 10,
    { align: "center" }
  );
}
