import { getAnswerCardsPerPage } from "../core/worksheetLayout.js";
import { getTemplatePresentation } from "../templates/templates.js";

function getPdfFontFamily(template) {
  if (template.layout === "single-column") {
    return "times";
  }

  return "helvetica";
}

function hexToRgb(hexColor) {
  const normalized = String(hexColor || "").replace("#", "");

  if (normalized.length !== 6) {
    return { r: 0, g: 140, b: 255 };
  }

  return {
    r: Number.parseInt(normalized.slice(0, 2), 16),
    g: Number.parseInt(normalized.slice(2, 4), 16),
    b: Number.parseInt(normalized.slice(4, 6), 16)
  };
}

function buildQuestionRows(pdf, questions, presentation, questionFontSize, columnWidth) {
  const rows = [];
  const columnsCount = presentation.columnsCount;
  const boxPadding = 4;
  const lineHeight = Math.max(5.4, questionFontSize * 0.42);

  for (let index = 0; index < questions.length; index += columnsCount) {
    const rowQuestions = questions.slice(index, index + columnsCount).map((question, offset) => {
      const absoluteIndex = index + offset + 1;
      const label = `${absoluteIndex}. ${question.text}`;
      const textLines = pdf.splitTextToSize(label, columnWidth - (boxPadding * 2));
      const baseHeight = (textLines.length * lineHeight) + (question.answerLine === false ? 10 : 17);

      return {
        question,
        textLines,
        boxHeight: Math.max(18, baseHeight)
      };
    });

    rows.push({
      items: rowQuestions,
      rowHeight: Math.max(...rowQuestions.map((item) => item.boxHeight))
    });
  }

  return rows;
}

function paginateRows(rows, usableHeight, rowGap) {
  const pages = [];
  let currentPageRows = [];
  let usedHeight = 0;

  rows.forEach((row) => {
    const totalRowHeight = row.rowHeight + (currentPageRows.length > 0 ? rowGap : 0);

    if (currentPageRows.length > 0 && usedHeight + totalRowHeight > usableHeight) {
      pages.push(currentPageRows);
      currentPageRows = [row];
      usedHeight = row.rowHeight;
      return;
    }

    currentPageRows.push(row);
    usedHeight += totalRowHeight;
  });

  if (currentPageRows.length > 0) {
    pages.push(currentPageRows);
  }

  return pages;
}

function drawMetaPair(pdf, leftLabel, leftValue, rightLabel, rightValue, y, margins, pageWidth) {
  pdf.text(`${leftLabel}: ${leftValue}`, margins.left, y);
  pdf.text(`${rightLabel}: ${rightValue}`, pageWidth - margins.right, y, { align: "right" });
}

function drawPageChrome(pdf, {
  fontFamily,
  accentColor,
  identity,
  grade,
  subjectLabel,
  focusLabel,
  pageNumber,
  totalPages,
  margins,
  pageWidth,
  pageHeight,
  pageKind
}) {
  let y = margins.top;

  pdf.setTextColor(accentColor.r, accentColor.g, accentColor.b);
  pdf.setFont(fontFamily, "bold");

  if (identity.schoolName) {
    pdf.setFontSize(12);
    pdf.text(identity.schoolName, pageWidth / 2, y, { align: "center" });
    y += 7;
  }

  pdf.setFontSize(18);
  pdf.text(identity.worksheetTitle || "Worksheet", pageWidth / 2, y, { align: "center" });
  y += 8;

  if (pageKind === "answer-key") {
    pdf.setFontSize(11);
    pdf.text("Answer Sheet", pageWidth / 2, y, { align: "center" });
    y += 6.5;
  }

  pdf.setTextColor(20, 24, 39);
  pdf.setFont(fontFamily, "normal");
  pdf.setFontSize(10.2);
  drawMetaPair(
    pdf,
    "Teacher",
    identity.teacherName || "________________",
    "Student",
    identity.studentName || "________________",
    y,
    margins,
    pageWidth
  );
  y += 6.2;

  drawMetaPair(
    pdf,
    "Date",
    identity.worksheetDate || "________________",
    "Score",
    identity.scorePoints || "________________",
    y,
    margins,
    pageWidth
  );
  y += 6.2;

  drawMetaPair(
    pdf,
    "Level",
    grade || "--",
    "Subject",
    subjectLabel || "--",
    y,
    margins,
    pageWidth
  );
  y += 6.2;

  pdf.text(`Focus: ${focusLabel || "--"}`, margins.left, y);
  y += 5.5;

  if (identity.instructions) {
    const instructionLines = pdf.splitTextToSize(`Instructions: ${identity.instructions}`, pageWidth - margins.left - margins.right);
    pdf.setFillColor(247, 251, 255);
    pdf.setDrawColor(220, 232, 245);
    const boxHeight = Math.max(11, (instructionLines.length * 4.8) + 5);
    pdf.roundedRect(margins.left, y - 3.6, pageWidth - margins.left - margins.right, boxHeight, 2, 2, "FD");
    pdf.text(instructionLines, margins.left + 3, y);
    y += boxHeight + 1.5;
  }

  pdf.setDrawColor(accentColor.r, accentColor.g, accentColor.b);
  pdf.setLineWidth(0.45);
  pdf.line(margins.left, y, pageWidth - margins.right, y);

  pdf.setFont(fontFamily, "normal");
  pdf.setFontSize(9.4);
  pdf.setTextColor(90, 100, 114);
  pdf.line(margins.left, pageHeight - margins.bottom + 1.5, pageWidth - margins.right, pageHeight - margins.bottom + 1.5);
  pdf.text("Generated by TeachSheet AI", margins.left, pageHeight - margins.bottom + 6);
  pdf.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margins.right, pageHeight - margins.bottom + 6, {
    align: "right"
  });

  return y + 7;
}

function drawQuestionPages(pdf, questionPages, options) {
  const {
    fontFamily,
    accentColor,
    identity,
    grade,
    subjectLabel,
    focusLabel,
    margins,
    pageWidth,
    pageHeight,
    questionFontSize,
    columnWidth,
    columnGap,
    rowGap,
    totalPages
  } = options;

  questionPages.forEach((pageRows, pageIndex) => {
    if (pageIndex > 0) {
      pdf.addPage();
    }

    let y = drawPageChrome(pdf, {
      fontFamily,
      accentColor,
      identity,
      grade,
      subjectLabel,
      focusLabel,
      pageNumber: pageIndex + 1,
      totalPages,
      margins,
      pageWidth,
      pageHeight,
      pageKind: "questions"
    });

    pdf.setFont(fontFamily, "normal");
    pdf.setFontSize(questionFontSize);
    pdf.setTextColor(20, 24, 39);

    pageRows.forEach((row) => {
      row.items.forEach((item, itemIndex) => {
        const x = margins.left + (itemIndex * (columnWidth + columnGap));
        const boxHeight = row.rowHeight;

        pdf.setDrawColor(183, 217, 245);
        pdf.setFillColor(255, 255, 255);
        pdf.roundedRect(x, y, columnWidth, boxHeight, 3, 3, "FD");
        pdf.text(item.textLines, x + 4, y + 6);

        if (item.question.answerLine !== false) {
          pdf.line(x + 4, y + boxHeight - 5, x + columnWidth - 4, y + boxHeight - 5);
        }
      });

      y += row.rowHeight + rowGap;
    });
  });
}

function drawAnswerKeyPages(pdf, questions, options) {
  const {
    fontFamily,
    accentColor,
    identity,
    grade,
    subjectLabel,
    focusLabel,
    margins,
    pageWidth,
    pageHeight,
    totalPages,
    questionPageCount,
    template
  } = options;

  const cardsPerPage = getAnswerCardsPerPage(template);
  const presentation = getTemplatePresentation(template);
  const answerColumns = Math.min(4, presentation.columnsCount === 1 ? 3 : 4);
  const answerGap = 6;
  const cardHeight = 10;
  const answerColumnWidth = (
    pageWidth - margins.left - margins.right - ((answerColumns - 1) * answerGap)
  ) / answerColumns;
  const totalAnswerPages = Math.max(1, Math.ceil(questions.length / cardsPerPage));

  for (let pageIndex = 0; pageIndex < totalAnswerPages; pageIndex += 1) {
    const pageQuestions = questions.slice(pageIndex * cardsPerPage, (pageIndex + 1) * cardsPerPage);

    pdf.addPage();
    const startY = drawPageChrome(pdf, {
      fontFamily,
      accentColor,
      identity,
      grade,
      subjectLabel,
      focusLabel,
      pageNumber: questionPageCount + pageIndex + 1,
      totalPages,
      margins,
      pageWidth,
      pageHeight,
      pageKind: "answer-key"
    });

    pdf.setFont(fontFamily, "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(20, 24, 39);

    pageQuestions.forEach((question, localIndex) => {
      const columnIndex = localIndex % answerColumns;
      const rowIndex = Math.floor(localIndex / answerColumns);
      const x = margins.left + (columnIndex * (answerColumnWidth + answerGap));
      const y = startY + (rowIndex * (cardHeight + 4));
      const absoluteIndex = (pageIndex * cardsPerPage) + localIndex + 1;

      pdf.setDrawColor(220, 232, 245);
      pdf.setFillColor(247, 251, 255);
      pdf.roundedRect(x, y, answerColumnWidth, cardHeight, 2, 2, "FD");
      pdf.text(`${absoluteIndex}) ${question.answer}`, x + 3, y + 6.2);
    });
  }
}

export function downloadWorksheetPDF({
  questions,
  grade,
  template,
  theme,
  worksheetTitle,
  subjectLabel,
  focusLabel,
  showAnswerKey,
  identity
}) {
  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF({
    orientation: "p",
    unit: "mm",
    format: "a4",
    compress: true
  });
  const presentation = getTemplatePresentation(template);
  const fontFamily = getPdfFontFamily(presentation);
  const accentColor = hexToRgb(theme?.accent);
  const pageWidth = 210;
  const pageHeight = 297;
  const margins = {
    top: 14,
    right: 14,
    bottom: 12,
    left: 14
  };
  const estimatedHeaderHeight = identity?.instructions ? 58 : 46;
  const usableHeight = pageHeight - estimatedHeaderHeight - margins.bottom - 10;
  const rowGap = Math.max(5, Math.round(presentation.spacing * 0.28));
  const questionFontSize = Math.max(11.5, presentation.fontSize - 7);
  const columnGap = 8;
  const columnWidth = presentation.columnsCount === 1
    ? pageWidth - margins.left - margins.right
    : ((pageWidth - margins.left - margins.right - columnGap) / 2);
  const questionRows = buildQuestionRows(pdf, questions, presentation, questionFontSize, columnWidth);
  const questionPages = paginateRows(questionRows, usableHeight, rowGap);
  const answerPageCount = showAnswerKey ? Math.max(1, Math.ceil(questions.length / getAnswerCardsPerPage(template))) : 0;
  const totalPages = questionPages.length + answerPageCount;
  const resolvedIdentity = {
    worksheetTitle: identity?.worksheetTitle || worksheetTitle || "Worksheet",
    schoolName: identity?.schoolName || "",
    teacherName: identity?.teacherName || "",
    studentName: identity?.studentName || "",
    worksheetDate: identity?.worksheetDate || "",
    instructions: identity?.instructions || "",
    scorePoints: identity?.scorePoints || ""
  };

  drawQuestionPages(pdf, questionPages, {
    fontFamily,
    accentColor,
    identity: resolvedIdentity,
    grade,
    subjectLabel,
    focusLabel,
    margins,
    pageWidth,
    pageHeight,
    questionFontSize,
    columnWidth,
    columnGap,
    rowGap,
    totalPages
  });

  if (showAnswerKey) {
    drawAnswerKeyPages(pdf, questions, {
      fontFamily,
      accentColor,
      identity: resolvedIdentity,
      grade,
      subjectLabel,
      focusLabel,
      margins,
      pageWidth,
      pageHeight,
      totalPages,
      questionPageCount: questionPages.length,
      template
    });
  }

  pdf.save("teachsheet-ai-worksheet.pdf");
}
