import { getTemplatePresentation } from "../templates/templates.js";

function escapeHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function formatMultilineText(value = "") {
  return escapeHtml(value).replaceAll("\n", "<br />");
}

function buildMetaValue(value, fallback = "________________") {
  return escapeHtml(value || fallback);
}

function createQuestionMarkup(question, index, startIndex) {
  return `
    <div class="question">
      <span class="question-number"><strong>${startIndex + index + 1}.</strong></span>
      ${escapeHtml(question.text)}
      ${question.answerLine === false ? "" : '<span class="answer-line"></span>'}
    </div>
  `;
}

function createAnswerKeyMarkup(questions) {
  return questions
    .map((question) => `<div class="answer-item">${escapeHtml(String(question.answerIndex || ""))}) ${escapeHtml(question.answer)}</div>`)
    .join("");
}

function createIdentityMetaMarkup({
  identity,
  grade,
  subjectLabel,
  focusLabel
}) {
  const metaItems = [
    ["Teacher", identity.teacherName],
    ["Student", identity.studentName],
    ["Date", identity.worksheetDate],
    ["Score", identity.scorePoints],
    ["Level", grade || "--"],
    ["Subject", subjectLabel],
    ["Focus", focusLabel]
  ];

  return metaItems.map(([label, value]) => `
    <div class="meta-item">
      <strong>${escapeHtml(label)}:</strong>
      <span>${buildMetaValue(value)}</span>
    </div>
  `).join("");
}

function createInstructionsMarkup(instructions = "") {
  if (!instructions) {
    return "";
  }

  return `
    <div class="worksheet-instructions">
      <strong>Instructions</strong>
      <p>${formatMultilineText(instructions)}</p>
    </div>
  `;
}

function createWorksheetHeaderMarkup({
  identity,
  grade,
  subjectLabel,
  focusLabel,
  currentPage,
  totalPages,
  pageKind
}) {
  return `
    <div class="worksheet-header">
      ${identity.schoolName ? `<div class="worksheet-school">${escapeHtml(identity.schoolName)}</div>` : ""}
      <div class="worksheet-title-row">
        <div>
          <h2>${escapeHtml(identity.worksheetTitle || "Worksheet")}</h2>
          ${pageKind === "answer-key" ? '<div class="worksheet-page-type">Answer Sheet</div>' : ""}
        </div>
        <div class="worksheet-page-badge">Page ${currentPage} of ${totalPages}</div>
      </div>
      <div class="meta worksheet-meta-grid">
        ${createIdentityMetaMarkup({ identity, grade, subjectLabel, focusLabel })}
      </div>
      ${createInstructionsMarkup(identity.instructions)}
    </div>
  `;
}

function createWorksheetFooterMarkup(currentPage, totalPages) {
  return `
    <div class="worksheet-footer">
      <span>Generated by TeachSheet AI</span>
      <span>Page ${currentPage} of ${totalPages}</span>
    </div>
  `;
}

function applyTemplatePresentation(worksheetElement, template) {
  const presentation = getTemplatePresentation(template);

  worksheetElement.style.setProperty("--worksheet-font-family", presentation.fontFamily);
  worksheetElement.style.setProperty("--questions-columns", presentation.columns);
  worksheetElement.style.setProperty("--questions-gap", `${presentation.questionsGap}px`);
  worksheetElement.style.setProperty("--question-font-size", `${presentation.fontSize}px`);
  worksheetElement.style.setProperty("--question-padding", `${presentation.questionPadding}px`);
  worksheetElement.style.setProperty("--question-radius", `${presentation.questionRadius}px`);
  worksheetElement.style.setProperty("--question-border-style", presentation.questionBorderStyle);
  worksheetElement.style.setProperty("--question-background", presentation.questionBackground);
  worksheetElement.style.setProperty("--question-line-height", String(presentation.questionLineHeight));
  worksheetElement.style.setProperty("--answer-columns", presentation.answerColumns);
  worksheetElement.style.setProperty("--answer-gap", `${presentation.answerGap}px`);
}

export function renderWorksheetPreview({
  worksheetElement,
  grade,
  subjectLabel,
  focusLabel,
  questions,
  answerQuestions,
  currentPage,
  totalPages,
  template,
  pageSize,
  showAnswerKey,
  pageKind,
  identity
}) {
  const isAnswerPage = pageKind === "answer-key" && showAnswerKey;
  const questionStartIndex = (currentPage - 1) * pageSize;

  worksheetElement.innerHTML = `
    ${createWorksheetHeaderMarkup({
      identity,
      grade,
      subjectLabel,
      focusLabel,
      currentPage,
      totalPages,
      pageKind
    })}
    ${isAnswerPage ? `
      <div class="answer-key standalone-answer-key">
        <h3>Answer Sheet</h3>
        <div class="answer-grid">
          ${createAnswerKeyMarkup(answerQuestions)}
        </div>
      </div>
    ` : `
      <div id="questions" class="questions">
        ${questions.map((question, index) => createQuestionMarkup(question, index, questionStartIndex)).join("")}
      </div>
    `}
    ${createWorksheetFooterMarkup(currentPage, totalPages)}
  `;

  applyTemplatePresentation(worksheetElement, template);
  worksheetElement.dataset.previewPage = String(currentPage);
  worksheetElement.dataset.previewTotalPages = String(totalPages);
  worksheetElement.dataset.templateId = template.id;
}

export function renderEmptyWorksheet(worksheetElement, template) {
  worksheetElement.innerHTML = `
    <div class="worksheet-header">
      <h2>Worksheet</h2>
      <p>Complete the worksheet identity, then generate a printable school-ready sheet.</p>
    </div>
    <div id="questions" class="questions empty">
      <div class="empty-state">
        <h3>No worksheet generated yet.</h3>
        <p>Use the identity fields for school-ready details, then generate a worksheet to preview page numbering, header layout, and printable content.</p>
      </div>
    </div>
    ${createWorksheetFooterMarkup(1, 1)}
  `;

  applyTemplatePresentation(worksheetElement, template);
  worksheetElement.dataset.previewPage = "1";
  worksheetElement.dataset.previewTotalPages = "1";
  worksheetElement.dataset.templateId = template.id;
}
