function escapeHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function createQuestionMarkup(question, index) {
  return `
    <div class="question">
      <strong>${index + 1}.</strong> ${escapeHtml(question.text)} <span class="answer-line"></span>
    </div>
  `;
}

function createAnswerKeyMarkup(questions) {
  return questions.map((question, index) => `<div>${index + 1}) ${escapeHtml(question.answer)}</div>`).join("");
}

export function renderWorksheetPreview({
  worksheetElement,
  grade,
  operation,
  difficulty,
  studentName,
  questions,
  currentPage,
  totalPages,
  formatOperation,
  capitalize
}) {
  worksheetElement.innerHTML = `
    <div class="worksheet-header">
      <h2>Math Worksheet</h2>
      <p>Generated by TeachSheet AI</p>
      <div class="meta">
        <div><strong>Name:</strong> ${escapeHtml(studentName || "________________")}</div>
        <div><strong>Grade:</strong> ${escapeHtml(grade)}</div>
        <div><strong>Operation:</strong> ${escapeHtml(formatOperation(operation))}</div>
        <div><strong>Difficulty:</strong> ${escapeHtml(capitalize(difficulty))}</div>
      </div>
    </div>
    <div id="questions" class="questions">
      ${questions.map((question, index) => createQuestionMarkup(question, index)).join("")}
    </div>
    <div class="answer-key">
      <h3>Answer Key</h3>
      <div class="answer-grid">
        ${createAnswerKeyMarkup(questions)}
      </div>
    </div>
  `;

  worksheetElement.dataset.previewPage = String(currentPage);
  worksheetElement.dataset.previewTotalPages = String(totalPages);
}

export function renderEmptyWorksheet(worksheetElement) {
  worksheetElement.innerHTML = `
    <div class="worksheet-header">
      <h2>Math Worksheet</h2>
      <p>Choose settings and click Generate Worksheet.</p>
    </div>
    <div id="questions" class="questions empty">No worksheet generated yet.</div>
  `;

  worksheetElement.dataset.previewPage = "1";
  worksheetElement.dataset.previewTotalPages = "1";
}
